//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSM2018.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\majitaki\\Anaconda3\\Scripts\\activate.bat")]
        public string AnacondaPath {
            get {
                return ((string)(this["AnacondaPath"]));
            }
            set {
                this["AnacondaPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AnacondaEnv {
            get {
                return ((string)(this["AnacondaEnv"]));
            }
            set {
                this["AnacondaEnv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./Resources/PythonScript/NetworkGenerator/")]
        public string NetworkGeneratorPath {
            get {
                return ((string)(this["NetworkGeneratorPath"]));
            }
            set {
                this["NetworkGeneratorPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./Resources/Output/Working/")]
        public string NetworkOutput {
            get {
                return ((string)(this["NetworkOutput"]));
            }
            set {
                this["NetworkOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./Resources/PythonScript/LayoutGenerator/")]
        public string LayoutGeneratorPath {
            get {
                return ((string)(this["LayoutGeneratorPath"]));
            }
            set {
                this["LayoutGeneratorPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\majitaki\\Anaconda3\\Scripts\\activate.bat")]
        public string lab_path {
            get {
                return ((string)(this["lab_path"]));
            }
            set {
                this["lab_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\ProgramData\\Anaconda3\\Scripts\\activate.bat")]
        public string home_path {
            get {
                return ((string)(this["home_path"]));
            }
            set {
                this["home_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ProgramData\\Anaconda3\\Scripts\\activate.bat")]
        public string kaigi_path {
            get {
                return ((string)(this["kaigi_path"]));
            }
            set {
                this["kaigi_path"] = value;
            }
        }
    }
}
